export const BLOG_REQUEST = "BLOG_REQUEST";
export const BLOG_FAILURE = "BLOG_FAILURE";

export const BLOG_GET_SUCCESS = "BLOG_GET_SUCCESS";
export const BLOG_POST_SUCCESS = "BLOG_POST_SUCCESS";
export const BLOG_PATCH_SUCCESS = "BLOG_PATCH_SUCCESS";
export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS";
